name: DevSecOps Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  scan-and-analyze:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Scan IaC avec Checkov
    - name: Run Checkov
      run: |
        docker run --rm -v ${{ github.workspace }}:/iac bridgecrew/checkov -d /iac --soft-fail

    # Scan vulnérabilités avec Trivy
    - name: Run Trivy
      run: |
        docker run --rm -v ${{ github.workspace }}:/project aquasec/trivy fs /project

    # Analyse SonarQube
    - name: Analyse de code avec SonarCloud
      uses: SonarSource/sonarcloud-github-action@v2
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

